name: aws-vpc-operator
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/aws-vpc-operator
  tag: v0.0.1
  pullPolicy: IfNotPresent
